# Generated by Django 5.0.1 on 2024-02-06 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('image', models.ImageField(null=True, upload_to='img')),
                ('discription', models.CharField(max_length=100)),
                ('Category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom.category')),
            ],
        ),
    ]
